import { PronounItem, PronounGroup } from './type';

export const DATA_RAW: Omit<PronounItem, 'index'>[] = [
  // 01. Personal / Possessive / Reflexive
  {
    group: PronounGroup.Personal,
    term: 'I',
    ipa: '/aɪ/',
    jp: '私は',
    exJ1: 'I am fifteen.',
    exJ2: "I don't have any homework today.",
    exJ3: 'I have never been abroad.',
    exJ1Jp: '私は15歳です。',
    exJ2Jp: '今日は宿題がありません。',
    exJ3Jp: '私は海外に行ったことがありません。',
  },
  {
    group: PronounGroup.Personal,
    term: 'my',
    ipa: '/maɪ/',
    jp: '私の',
    exJ1: 'This is my bag.',
    exJ2: 'My sister plays the piano.',
    exJ3: 'My dream is to study overseas.',
    exJ1Jp: 'これは私のカバンです。',
    exJ2Jp: '私の妹はピアノを弾きます。',
    exJ3Jp: '私の夢は海外で勉強することです。',
  },
  {
    group: PronounGroup.Personal,
    term: 'me',
    ipa: '/miː/',
    jp: '私を、私に',
    exJ1: 'Please help me.',
    exJ2: 'Could you call me later?',
    exJ3: 'Everyone trusted me during the project.',
    exJ1Jp: '私を手伝ってください。',
    exJ2Jp: '後で私に電話してくれますか。',
    exJ3Jp: 'そのプロジェクトの間、皆が私を信頼してくれました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'mine',
    ipa: '/maɪn/',
    jp: '私のもの',
    exJ1: 'That pen is mine.',
    exJ2: 'The bigger one is mine.',
    exJ3: 'This seat was reserved, and it is mine.',
    exJ1Jp: 'そのペンは私のものです。',
    exJ2Jp: '大きい方は私のものです。',
    exJ3Jp: 'この席は予約してあって、私のものです。',
  },
  {
    group: PronounGroup.Personal,
    term: 'myself',
    ipa: '/maɪˈsɛlf/',
    jp: '私自身',
    exJ1: 'I made lunch by myself.',
    exJ2: 'I taught myself basic coding.',
    exJ3: 'I challenged myself to speak only English today.',
    exJ1Jp: '私は一人で昼ごはんを作りました。',
    exJ2Jp: '私は独学で基礎的なコーディングを学びました。',
    exJ3Jp: '今日は英語だけで話すことに自分で挑戦しました。',
  },

  {
    group: PronounGroup.Personal,
    term: 'we',
    ipa: '/wiː/',
    jp: '私たちは',
    exJ1: 'We are in the same class.',
    exJ2: 'We are studying for the test now.',
    exJ3: 'We have known each other since last year.',
    exJ1Jp: '私たちは同じクラスです。',
    exJ2Jp: '私たちは今テストの勉強をしています。',
    exJ3Jp: '私たちは去年からお互いを知っています。',
  },
  {
    group: PronounGroup.Personal,
    term: 'our',
    ipa: '/ˈaʊɚ/',
    jp: '私たちの',
    exJ1: 'This is our classroom.',
    exJ2: 'Our team will practice after school.',
    exJ3: 'Our teacher has given us extra homework.',
    exJ1Jp: 'これは私たちの教室です。',
    exJ2Jp: '私たちのチームは放課後に練習します。',
    exJ3Jp: '私たちの先生は追加の宿題を出しました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'us',
    ipa: '/ʌs/',
    jp: '私たちを、私たちに',
    exJ1: 'Please wait for us.',
    exJ2: 'The coach told us to run faster.',
    exJ3: 'They invited us to join the project.',
    exJ1Jp: '私たちを待ってください。',
    exJ2Jp: 'コーチは私たちにもっと速く走るよう言いました。',
    exJ3Jp: '彼らは私たちをプロジェクトに招待しました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'ours',
    ipa: '/ˈaʊɚz/',
    jp: '私たちのもの',
    exJ1: 'That desk is ours.',
    exJ2: 'The blue bags are ours.',
    exJ3: 'This win is ours, not theirs.',
    exJ1Jp: 'あの机は私たちのものです。',
    exJ2Jp: '青いカバンは私たちのものです。',
    exJ3Jp: 'この勝利は彼らではなく私たちのものです。',
  },
  {
    group: PronounGroup.Personal,
    term: 'ourselves',
    ipa: '/ɑrˈsɛlvz/',
    jp: '私たち自身',
    exJ1: 'We made sandwiches by ourselves.',
    exJ2: 'We introduced ourselves to the new students.',
    exJ3: 'We challenged ourselves to speak English all day.',
    exJ1Jp: '私たちは自分たちでサンドイッチを作りました。',
    exJ2Jp: '私たちは新入生に自分たちを紹介しました。',
    exJ3Jp: '私たちは一日中英語だけで話すことに挑戦しました。',
  },

  {
    group: PronounGroup.Personal,
    term: 'you',
    ipa: '/juː/',
    jp: 'あなたは',
    exJ1: 'You are my friend.',
    exJ2: 'You should bring a jacket today.',
    exJ3: 'You have grown more confident this year.',
    exJ1Jp: 'あなたは私の友だちです。',
    exJ2Jp: '今日は上着を持ってきたほうがいいです。',
    exJ3Jp: 'あなたは今年、前より自信がつきました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'your',
    ipa: '/jʊr/',
    jp: 'あなたの',
    exJ1: 'Is this your book?',
    exJ2: 'Your phone is ringing.',
    exJ3: 'Your idea has helped the team a lot.',
    exJ1Jp: 'これはあなたの本ですか？',
    exJ2Jp: 'あなたの電話が鳴っています。',
    exJ3Jp: 'あなたのアイデアはチームにとても役立ちました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'you',
    ipa: '/juː/',
    jp: 'あなたを、あなたに',
    exJ1: 'I can help you.',
    exJ2: "I'll text you later.",
    exJ3: 'The teacher asked you to present first.',
    exJ1Jp: '私はあなたを手伝えます。',
    exJ2Jp: '後であなたにメッセージを送ります。',
    exJ3Jp: '先生はあなたに最初に発表するよう頼みました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'yours',
    ipa: '/jʊrz/',
    jp: 'あなたのもの',
    exJ1: 'Is this pencil yours?',
    exJ2: 'That seat is yours.',
    exJ3: 'The final decision is yours.',
    exJ1Jp: 'このえんぴつはあなたのものですか？',
    exJ2Jp: 'あの席はあなたのものです。',
    exJ3Jp: '最終決定はあなたのものです（あなたが決めます）。',
  },
  {
    group: PronounGroup.Personal,
    term: 'yourself',
    ipa: '/jʊrˈsɛlf/',
    jp: 'あなた自身',
    exJ1: 'You can do it by yourself.',
    exJ2: 'Please take care of yourself.',
    exJ3: 'You challenged yourself to run a marathon.',
    exJ1Jp: 'あなたは一人でそれができます。',
    exJ2Jp: '自分の体に気をつけてください。',
    exJ3Jp: 'あなたはマラソンに挑戦しました（自分自身に課しました）。',
  },

  {
    group: PronounGroup.Personal,
    term: 'you',
    ipa: '/juː/',
    jp: 'あなたたちは',
    exJ1: 'You all are early today.',
    exJ2: 'You are practicing hard these days.',
    exJ3: 'You have been working together for months.',
    exJ1Jp: 'あなたたちは今日は早いですね。',
    exJ2Jp: 'あなたたちは最近、一生けん命練習しています。',
    exJ3Jp: 'あなたたちは数か月間、一緒に取り組んできました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'your',
    ipa: '/jʊr/',
    jp: 'あなたたちの',
    exJ1: 'Is this your classroom?',
    exJ2: 'Your club starts at four.',
    exJ3: 'Your efforts have made a big difference.',
    exJ1Jp: 'これはあなたたちの教室ですか？',
    exJ2Jp: 'あなたたちのクラブは4時に始まります。',
    exJ3Jp: 'あなたたちの努力は大きな違いを生みました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'you',
    ipa: '/juː/',
    jp: 'あなたたちを、あなたたちに',
    exJ1: 'I will help you after school.',
    exJ2: 'The teacher gave you a quiz.',
    exJ3: 'I invited you to our event.',
    exJ1Jp: '放課後にあなたたちを手伝います。',
    exJ2Jp: '先生はあなたたちに小テストを出しました。',
    exJ3Jp: '私はあなたたちを私たちのイベントに招待しました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'yours',
    ipa: '/jʊrz/',
    jp: 'あなたたちのもの',
    exJ1: 'Are these notebooks yours?',
    exJ2: 'The front seats are yours.',
    exJ3: 'The choice is yours.',
    exJ1Jp: 'これらのノートはあなたたちのものですか？',
    exJ2Jp: '前の席はあなたたちのものです。',
    exJ3Jp: '選択はあなたたちに任されています。',
  },
  {
    group: PronounGroup.Personal,
    term: 'yourselves',
    ipa: '/jʊrˈsɛlvz/',
    jp: 'あなたたち自身',
    exJ1: 'Please line up by yourselves.',
    exJ2: 'Please introduce yourselves to the class.',
    exJ3: 'You prepared yourselves well for the contest.',
    exJ1Jp: '自分たちで並んでください。',
    exJ2Jp: 'クラスに自分たちの紹介をしてください。',
    exJ3Jp: 'あなたたちは大会に向けてしっかり準備しました。',
  },

  {
    group: PronounGroup.Personal,
    term: 'he',
    ipa: '/hiː/',
    jp: '彼は',
    exJ1: 'He is my brother.',
    exJ2: 'He plays soccer after school.',
    exJ3: 'He has lived in Osaka for five years.',
    exJ1Jp: '彼は私の兄です。',
    exJ2Jp: '彼は放課後にサッカーをします。',
    exJ3Jp: '彼は5年間大阪に住んでいます。',
  },
  {
    group: PronounGroup.Personal,
    term: 'his',
    ipa: '/hɪz/',
    jp: '彼の',
    exJ1: 'This is his bike.',
    exJ2: 'His father works in Tokyo.',
    exJ3: 'His advice has been helpful.',
    exJ1Jp: 'これは彼の自転車です。',
    exJ2Jp: '彼のお父さんは東京で働いています。',
    exJ3Jp: '彼の助言は役に立ってきました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'him',
    ipa: '/hɪm/',
    jp: '彼を、彼に',
    exJ1: 'I saw him at the station.',
    exJ2: 'Please give him this note.',
    exJ3: 'Everyone respects him.',
    exJ1Jp: '駅で彼を見ました。',
    exJ2Jp: 'このメモを彼に渡してください。',
    exJ3Jp: 'みんなが彼を尊敬しています。',
  },
  {
    group: PronounGroup.Personal,
    term: 'his',
    ipa: '/hɪz/',
    jp: '彼のもの',
    exJ1: 'This seat is his.',
    exJ2: 'That pencil case is his.',
    exJ3: 'The final decision is his.',
    exJ1Jp: 'この席は彼のものです。',
    exJ2Jp: 'あのペンケースは彼のものです。',
    exJ3Jp: '最終的な決定は彼のものです。',
  },
  {
    group: PronounGroup.Personal,
    term: 'himself',
    ipa: '/hɪmˈsɛlf/',
    jp: '彼自身',
    exJ1: 'He cut the cake by himself.',
    exJ2: 'He taught himself guitar.',
    exJ3: 'He blamed himself for the mistake.',
    exJ1Jp: '彼は一人でケーキを切りました。',
    exJ2Jp: '彼は独学でギターを学びました。',
    exJ3Jp: '彼はその間違いを自分のせいだと責めました。',
  },

  {
    group: PronounGroup.Personal,
    term: 'she',
    ipa: '/ʃiː/',
    jp: '彼女は',
    exJ1: 'She is my sister.',
    exJ2: 'She is studying in the library.',
    exJ3: 'She has visited Kyoto many times.',
    exJ1Jp: '彼女は私の妹です。',
    exJ2Jp: '彼女は図書館で勉強しています。',
    exJ3Jp: '彼女は何度も京都を訪れています。',
  },
  {
    group: PronounGroup.Personal,
    term: 'her',
    ipa: '/hɝː/',
    jp: '彼女の',
    exJ1: 'Her bag is red.',
    exJ2: 'Her parents are doctors.',
    exJ3: 'Her idea has changed the plan.',
    exJ1Jp: '彼女のカバンは赤いです。',
    exJ2Jp: '彼女の両親は医者です。',
    exJ3Jp: '彼女の考えで計画が変わりました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'her',
    ipa: '/hɝː/',
    jp: '彼女を、彼女に',
    exJ1: 'I called her yesterday.',
    exJ2: 'Please tell her the time.',
    exJ3: 'We chose her as the leader.',
    exJ1Jp: '私は昨日彼女に電話しました。',
    exJ2Jp: '彼女に時間を伝えてください。',
    exJ3Jp: '私たちは彼女をリーダーに選びました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'hers',
    ipa: '/hɝːz/',
    jp: '彼女のもの',
    exJ1: 'This umbrella is hers.',
    exJ2: 'Those keys are hers.',
    exJ3: 'The victory is hers.',
    exJ1Jp: 'この傘は彼女のものです。',
    exJ2Jp: 'あの鍵は彼女のものです。',
    exJ3Jp: 'その勝利は彼女のものです。',
  },
  {
    group: PronounGroup.Personal,
    term: 'herself',
    ipa: '/hɝːˈsɛlf/',
    jp: '彼女自身',
    exJ1: 'She made it herself.',
    exJ2: 'She introduced herself in English.',
    exJ3: 'She taught herself to code.',
    exJ1Jp: '彼女はそれを自分で作りました。',
    exJ2Jp: '彼女は英語で自己紹介をしました。',
    exJ3Jp: '彼女は独学でプログラミングを学びました。',
  },

  {
    group: PronounGroup.Personal,
    term: 'it',
    ipa: '/ɪt/',
    jp: 'それは',
    exJ1: 'It is rainy today.',
    exJ2: 'It looks fun.',
    exJ3: 'It has become colder recently.',
    exJ1Jp: '今日は雨です。',
    exJ2Jp: 'それは楽しそうです。',
    exJ3Jp: '最近、寒くなってきました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'its',
    ipa: '/ɪts/',
    jp: 'それの',
    exJ1: 'The dog wagged its tail.',
    exJ2: 'This town is known for its river.',
    exJ3: 'The company changed its policy.',
    exJ1Jp: '犬はしっぽを振りました。',
    exJ2Jp: 'この町は川で知られています。',
    exJ3Jp: 'その会社は方針を変えました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'it',
    ipa: '/ɪt/',
    jp: 'それを、それに',
    exJ1: 'I like it.',
    exJ2: 'I found it online.',
    exJ3: 'I considered it carefully.',
    exJ1Jp: '私はそれが好きです。',
    exJ2Jp: '私はそれをオンラインで見つけました。',
    exJ3Jp: '私はそれを慎重に考えました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'itself',
    ipa: '/ɪtˈsɛlf/',
    jp: 'それ自身',
    exJ1: 'The door opened by itself.',
    exJ2: 'The machine stops by itself at night.',
    exJ3: 'The problem solved itself after the update.',
    exJ1Jp: 'ドアは自然に開きました。',
    exJ2Jp: 'その機械は夜に自動で止まります。',
    exJ3Jp: 'アップデート後、その問題は自然に解決しました。',
  },

  {
    group: PronounGroup.Personal,
    term: 'they',
    ipa: '/ðeɪ/',
    jp: '彼らは',
    exJ1: 'They are classmates.',
    exJ2: 'They are playing basketball now.',
    exJ3: 'They have traveled to many countries.',
    exJ1Jp: '彼らはクラスメイトです。',
    exJ2Jp: '彼らは今バスケットボールをしています。',
    exJ3Jp: '彼らは多くの国を旅行したことがあります。',
  },
  {
    group: PronounGroup.Personal,
    term: 'their',
    ipa: '/ðɛr/',
    jp: '彼らの',
    exJ1: 'Their house is big.',
    exJ2: 'Their teacher is kind.',
    exJ3: 'Their efforts have paid off.',
    exJ1Jp: '彼らの家は大きいです。',
    exJ2Jp: '彼らの先生は親切です。',
    exJ3Jp: '彼らの努力は実を結びました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'them',
    ipa: '/ðɛm/',
    jp: '彼らを、彼らに',
    exJ1: 'I saw them on the train.',
    exJ2: 'Please give them water.',
    exJ3: 'I asked them to join us.',
    exJ1Jp: '電車で彼らを見ました。',
    exJ2Jp: '彼らに水をあげてください。',
    exJ3Jp: '私は彼らに一緒に参加するよう頼みました。',
  },
  {
    group: PronounGroup.Personal,
    term: 'theirs',
    ipa: '/ðɛrz/',
    jp: '彼らのもの',
    exJ1: 'This ball is theirs.',
    exJ2: 'The seats near the front are theirs.',
    exJ3: 'The win is theirs this time.',
    exJ1Jp: 'このボールは彼らのものです。',
    exJ2Jp: '前の方の席は彼らのものです。',
    exJ3Jp: '今回は彼らの勝ちです。',
  },
  {
    group: PronounGroup.Personal,
    term: 'themselves',
    ipa: '/ðɛmˈsɛlvz/',
    jp: '彼ら自身',
    exJ1: 'They cooked dinner by themselves.',
    exJ2: 'They introduced themselves to the new teacher.',
    exJ3: 'They pushed themselves to the limit.',
    exJ1Jp: '彼らは自分たちで夕食を作りました。',
    exJ2Jp: '彼らは新しい先生に自己紹介しました。',
    exJ3Jp: '彼らは限界まで自分たちを追い込みました。',
  },

  // 02. Indefinite (person/thing)
  {
    group: PronounGroup.IndefPersonThing,
    term: 'someone',
    ipa: '/ˈsʌmˌwʌn/',
    jp: '誰か',
    exJ1: 'Someone is at the door.',
    exJ2: 'Someone called me last night.',
    exJ3: 'Someone has taken my seat.',
    exJ1Jp: '誰かがドアのところにいます。',
    exJ2Jp: '昨夜、誰かが私に電話をしました。',
    exJ3Jp: '誰かが私の席を取ってしまいました。',
  },
  {
    group: PronounGroup.IndefPersonThing,
    term: 'somebody',
    ipa: '/ˈsʌmˌbɑːdi/',
    jp: '誰か',
    exJ1: 'Somebody dropped this card.',
    exJ2: 'Somebody will help you soon.',
    exJ3: 'Somebody has already cleaned the room.',
    exJ1Jp: '誰かがこのカードを落としました。',
    exJ2Jp: '誰かがすぐあなたを手伝ってくれます。',
    exJ3Jp: '誰かがすでに部屋を掃除しました。',
  },
  {
    group: PronounGroup.IndefPersonThing,
    term: 'something',
    ipa: '/ˈsʌmˌθɪŋ/',
    jp: '何か',
    exJ1: 'I want something to drink.',
    exJ2: 'Something smells good.',
    exJ3: 'Something has changed recently.',
    exJ1Jp: '何か飲み物が欲しいです。',
    exJ2Jp: '何かいい匂いがします。',
    exJ3Jp: '最近、何かが変わりました。',
  },

  {
    group: PronounGroup.IndefPersonThing,
    term: 'anyone',
    ipa: '/ˈɛniˌwʌn/',
    jp: '誰でも、誰か',
    exJ1: 'Anyone can join.',
    exJ2: 'Did anyone see my pen?',
    exJ3: 'If anyone needs help, let me know.',
    exJ1Jp: '誰でも参加できます。',
    exJ2Jp: '誰か私のペンを見ましたか？',
    exJ3Jp: 'もし誰か助けが必要なら知らせてください。',
  },
  {
    group: PronounGroup.IndefPersonThing,
    term: 'anybody',
    ipa: '/ˈɛniˌbɑːdi/',
    jp: '誰でも、誰か',
    exJ1: 'Is anybody here?',
    exJ2: 'Anybody can try this game.',
    exJ3: 'If anybody has questions, ask me later.',
    exJ1Jp: '誰かここにいますか？',
    exJ2Jp: '誰でもこのゲームを試せます。',
    exJ3Jp: 'もし質問がある人は、後で私に聞いてください。',
  },
  {
    group: PronounGroup.IndefPersonThing,
    term: 'anything',
    ipa: '/ˈɛniˌθɪŋ/',
    jp: '何でも、何か',
    exJ1: 'Do you want anything?',
    exJ2: 'You can buy anything at that store.',
    exJ3: 'If anything goes wrong, call me.',
    exJ1Jp: '何か欲しいですか？',
    exJ2Jp: 'その店では何でも買えます。',
    exJ3Jp: 'もし何か問題が起きたら、私に電話してください。',
  },

  {
    group: PronounGroup.IndefPersonThing,
    term: 'everyone',
    ipa: '/ˈɛvriˌwʌn/',
    jp: 'みんな',
    exJ1: 'Everyone is here.',
    exJ2: 'Everyone enjoyed the game.',
    exJ3: 'Everyone has done their homework.',
    exJ1Jp: 'みんなここにいます。',
    exJ2Jp: 'みんながその試合を楽しみました。',
    exJ3Jp: 'みんな宿題を終えています。',
  },
  {
    group: PronounGroup.IndefPersonThing,
    term: 'everybody',
    ipa: '/ˈɛvriˌbɑːdi/',
    jp: 'みんな',
    exJ1: 'Everybody likes music.',
    exJ2: 'Everybody was excited yesterday.',
    exJ3: 'Everybody has arrived on time.',
    exJ1Jp: 'みんな音楽が好きです。',
    exJ2Jp: '昨日はみんながわくわくしていました。',
    exJ3Jp: 'みんな時間どおりに到着しました。',
  },
  {
    group: PronounGroup.IndefPersonThing,
    term: 'everything',
    ipa: '/ˈɛvriˌθɪŋ/',
    jp: 'すべて',
    exJ1: 'Everything is okay.',
    exJ2: 'Everything looks new.',
    exJ3: 'Everything has been prepared.',
    exJ1Jp: 'すべて大丈夫です。',
    exJ2Jp: 'すべて新しく見えます。',
    exJ3Jp: 'すべて準備ができています。',
  },

  {
    group: PronounGroup.IndefPersonThing,
    term: 'no one',
    ipa: '/ˈnoʊ ˌwʌn/',
    jp: '誰も〜ない',
    exJ1: 'No one is in the room.',
    exJ2: 'No one answered the phone.',
    exJ3: 'No one has solved the puzzle yet.',
    exJ1Jp: '部屋には誰もいません。',
    exJ2Jp: '電話に誰も出ませんでした。',
    exJ3Jp: 'まだ誰もそのパズルを解いていません。',
  },
  {
    group: PronounGroup.IndefPersonThing,
    term: 'nobody',
    ipa: '/ˈnoʊˌbɑːdi/',
    jp: '誰も〜ない',
    exJ1: 'Nobody knows the answer.',
    exJ2: 'Nobody came to the club yesterday.',
    exJ3: 'Nobody has finished the task yet.',
    exJ1Jp: '答えを知っている人はいません。',
    exJ2Jp: '昨日はクラブに誰も来ませんでした。',
    exJ3Jp: 'まだ誰もその課題を終えていません。',
  },
  {
    group: PronounGroup.IndefPersonThing,
    term: 'nothing',
    ipa: '/ˈnʌθɪŋ/',
    jp: '何も〜ない',
    exJ1: 'Nothing is in the box.',
    exJ2: 'Nothing changed yesterday.',
    exJ3: 'Nothing has been decided yet.',
    exJ1Jp: '箱の中には何もありません。',
    exJ2Jp: '昨日は何も変わりませんでした。',
    exJ3Jp: 'まだ何も決まっていません。',
  },

  // 03. Indefinite (quantity/partitive)
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'one',
    ipa: '/wʌn/',
    jp: '一人、もの',
    exJ1: 'One is missing.',
    exJ2: 'Take one and pass it on.',
    exJ3: 'One of my friends has moved to Nagoya.',
    exJ1Jp: '一つ足りません。',
    exJ2Jp: '一つ取って次の人に回してください。',
    exJ3Jp: '友だちの一人が名古屋に引っ越しました。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'another',
    ipa: '/əˈnʌðɚ/',
    jp: 'もう一つの、別の',
    exJ1: 'I want another apple.',
    exJ2: 'Can I have another chance?',
    exJ3: "Let's try another way to solve it.",
    exJ1Jp: 'もう一つリンゴが欲しいです。',
    exJ2Jp: 'もう一度チャンスをもらえますか？',
    exJ3Jp: 'それを解く別の方法を試しましょう。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'other',
    ipa: '/ˈʌðɚ/',
    jp: '他の',
    exJ1: 'Show me other pictures.',
    exJ2: 'Other people are waiting.',
    exJ3: 'Other options have been suggested.',
    exJ1Jp: '他の写真を見せてください。',
    exJ2Jp: '他の人たちが待っています。',
    exJ3Jp: '他の選択肢が提案されています。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'others',
    ipa: '/ˈʌðɚz/',
    jp: '他のもの、人々',
    exJ1: 'Help others.',
    exJ2: 'Some study; others play.',
    exJ3: 'Others have already left.',
    exJ1Jp: '他の人を助けましょう。',
    exJ2Jp: '勉強する人もいれば、遊ぶ人もいます。',
    exJ3Jp: '他の人たちはすでに出発しました。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'each',
    ipa: '/itʃ/',
    jp: 'それぞれ',
    exJ1: 'Each student has a desk.',
    exJ2: 'We gave each person a number.',
    exJ3: 'Each of them has finished their work.',
    exJ1Jp: '生徒はそれぞれ机があります。',
    exJ2Jp: '私たちは一人ひとりに番号を渡しました。',
    exJ3Jp: '彼らはそれぞれ自分の作業を終えています。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'either',
    ipa: '/ˈiðɚ/',
    jp: 'どちらか',
    exJ1: 'Either is fine.',
    exJ2: 'You can choose either book.',
    exJ3: 'Either of the answers is acceptable.',
    exJ1Jp: 'どちらでも大丈夫です。',
    exJ2Jp: 'どちらの本でも選べます。',
    exJ3Jp: 'どちらの答えでも受け入れられます。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'neither',
    ipa: '/ˈniðɚ/',
    jp: 'どちらも〜ない',
    exJ1: 'Neither is correct.',
    exJ2: 'Neither team won yesterday.',
    exJ3: 'Neither of us has finished yet.',
    exJ1Jp: 'どちらも正しくありません。',
    exJ2Jp: '昨日はどちらのチームも勝ちませんでした。',
    exJ3Jp: '私たちのどちらもまだ終わっていません。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'none',
    ipa: '/nʌn/',
    jp: 'どれも〜ない、誰も〜ない',
    exJ1: 'None are left.',
    exJ2: 'None of the cookies are left.',
    exJ3: 'None of them have arrived yet.',
    exJ1Jp: '残りは一つもありません。',
    exJ2Jp: 'クッキーは一つも残っていません。',
    exJ3Jp: '彼らはまだ誰も到着していません。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'some',
    ipa: '/sʌm/',
    jp: 'いくつかの',
    exJ1: 'I have some.',
    exJ2: 'Would you like some?',
    exJ3: 'Some of the ideas have been chosen.',
    exJ1Jp: '私はいくつか持っています。',
    exJ2Jp: '少しいかがですか？',
    exJ3Jp: 'アイデアのいくつかが選ばれました。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'any',
    ipa: '/ˈɛni/',
    jp: 'いくらか、どれか',
    exJ1: "I don't have any.",
    exJ2: 'Do you have any time?',
    exJ3: 'If you have any questions, ask later.',
    exJ1Jp: '私は一つも持っていません。',
    exJ2Jp: '少し時間はありますか？',
    exJ3Jp: 'もし質問があれば、後で聞いてください。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'certain',
    ipa: '/ˈsɝːtn/',
    jp: 'ある人々',
    exJ1: 'Certain students are absent today.',
    exJ2: 'I have a certain plan in mind.',
    exJ3: 'Certain areas have been closed for safety.',
    exJ1Jp: '今日は特定の生徒が欠席しています。',
    exJ2Jp: '私はある計画を心に決めています。',
    exJ3Jp: '安全のため、特定の区域が閉鎖されています。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'all',
    ipa: '/ɔl/',
    jp: 'すべて',
    exJ1: 'All are welcome.',
    exJ2: 'All the students are here.',
    exJ3: 'All of us have finished.',
    exJ1Jp: '誰でも歓迎です。',
    exJ2Jp: '生徒は全員ここにいます。',
    exJ3Jp: '私たちは全員終わりました。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'both',
    ipa: '/boʊθ/',
    jp: '両方',
    exJ1: 'Both are ready.',
    exJ2: 'Both teams practiced hard.',
    exJ3: 'Both of them have improved a lot.',
    exJ1Jp: '両方とも準備ができています。',
    exJ2Jp: '両チームとも一生けん命練習しました。',
    exJ3Jp: '彼ら二人はとても上達しました。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'most',
    ipa: '/moʊst/',
    jp: 'ほとんどの',
    exJ1: 'Most students like music.',
    exJ2: 'Most of my friends play games.',
    exJ3: 'Most of the work has been done.',
    exJ1Jp: 'ほとんどの生徒は音楽が好きです。',
    exJ2Jp: '友だちのほとんどはゲームをします。',
    exJ3Jp: '作業のほとんどは終わっています。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'more',
    ipa: '/mɔr/',
    jp: 'もっと多くの',
    exJ1: 'I need more.',
    exJ2: 'We need more chairs.',
    exJ3: 'We need more information to decide.',
    exJ1Jp: 'もっと必要です。',
    exJ2Jp: 'もっとイスが必要です。',
    exJ3Jp: '判断するにはもっと情報が必要です。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'many',
    ipa: '/ˈmɛni/',
    jp: '多くの（可算）',
    exJ1: 'Many people came.',
    exJ2: 'Many students joined the club.',
    exJ3: 'Many of them have visited Tokyo.',
    exJ1Jp: '多くの人が来ました。',
    exJ2Jp: '多くの生徒がクラブに入りました。',
    exJ3Jp: '彼らの多くは東京を訪れたことがあります。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'much',
    ipa: '/mʌtʃ/',
    jp: '多くの（不可算）',
    exJ1: "I don't have much time.",
    exJ2: "There isn't much milk in the fridge.",
    exJ3: 'Much has changed since spring.',
    exJ1Jp: '私は時間があまりありません。',
    exJ2Jp: '冷蔵庫に牛乳があまりありません。',
    exJ3Jp: '春以来、多くのことが変わりました。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'several',
    ipa: '/ˈsɛvrəl/',
    jp: 'いくつかの',
    exJ1: 'Several students are absent.',
    exJ2: 'I visited several places last weekend.',
    exJ3: 'Several of the plans have been canceled.',
    exJ1Jp: '何人かの生徒が欠席しています。',
    exJ2Jp: '先週末にいくつかの場所を訪れました。',
    exJ3Jp: 'いくつかの計画が中止されました。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'few',
    ipa: '/fjuː/',
    jp: 'ほとんど〜ない（可算）',
    exJ1: 'Few buses come at night.',
    exJ2: 'I have few chances to speak English.',
    exJ3: 'Few of us have finished the report.',
    exJ1Jp: '夜はバスがほとんど来ません。',
    exJ2Jp: '英語を話す機会がほとんどありません。',
    exJ3Jp: '私たちの中でレポートを終えた人はほとんどいません。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'little',
    ipa: '/ˈlɪtl/',
    jp: 'ほとんど〜ない（不可算）',
    exJ1: 'I have little money.',
    exJ2: 'There is little time before the test.',
    exJ3: 'There is little hope of success.',
    exJ1Jp: '私はお金がほとんどありません。',
    exJ2Jp: 'テストまでほとんど時間がありません。',
    exJ3Jp: '成功の見込みはほとんどありません。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'less',
    ipa: '/lɛs/',
    jp: 'より少ない',
    exJ1: 'I need less salt.',
    exJ2: 'We have less time today.',
    exJ3: 'We spent less than last year.',
    exJ1Jp: '塩はもっと少なくていいです。',
    exJ2Jp: '今日は時間がより少ないです。',
    exJ3Jp: '私たちは昨年より少なく使いました。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'least',
    ipa: '/list/',
    jp: '最小、最も少ない',
    exJ1: 'I like this the least.',
    exJ2: 'This is the least useful item.',
    exJ3: 'She was the least affected by the change.',
    exJ1Jp: '私はこれが一番好きではありません。',
    exJ2Jp: 'これは最も役に立たない品です。',
    exJ3Jp: '彼女はその変化の影響を最も受けませんでした。',
  },
  {
    group: PronounGroup.IndefQuantityPartitive,
    term: 'enough',
    ipa: '/ɪˈnʌf/',
    jp: '十分な',
    exJ1: 'I have enough.',
    exJ2: 'We have enough chairs for everyone.',
    exJ3: 'We have enough time to finish the project.',
    exJ1Jp: '私は十分持っています。',
    exJ2Jp: 'みんな分のイスが十分あります。',
    exJ3Jp: 'そのプロジェクトを終えるのに十分な時間があります。',
  },

  // 04. Demonstrative & Other
  {
    group: PronounGroup.Demonstrative,
    term: 'this',
    ipa: '/ðɪs/',
    jp: 'これ',
    exJ1: 'This is my pen.',
    exJ2: 'This tastes sweet.',
    exJ3: 'This has become my favorite song.',
    exJ1Jp: 'これは私のペンです。',
    exJ2Jp: 'これは甘い味がします。',
    exJ3Jp: 'これは私のお気に入りの曲になりました。',
  },
  {
    group: PronounGroup.Demonstrative,
    term: 'these',
    ipa: '/ðiːz/',
    jp: 'これら',
    exJ1: 'These are my shoes.',
    exJ2: 'These look expensive.',
    exJ3: 'These have been very helpful.',
    exJ1Jp: 'これらは私の靴です。',
    exJ2Jp: 'これらは高そうに見えます。',
    exJ3Jp: 'これらはとても役立ってきました。',
  },
  {
    group: PronounGroup.Demonstrative,
    term: 'that',
    ipa: '/ðæt/',
    jp: 'それ、あれ',
    exJ1: 'That is our school.',
    exJ2: 'That sounds interesting.',
    exJ3: 'That has happened before.',
    exJ1Jp: 'あれは私たちの学校です。',
    exJ2Jp: 'それはおもしろそうに聞こえます。',
    exJ3Jp: 'それは以前にも起きたことがあります。',
  },
  {
    group: PronounGroup.Demonstrative,
    term: 'those',
    ipa: '/ðoʊz/',
    jp: 'それら、あれら',
    exJ1: 'Those are new bikes.',
    exJ2: 'Those look heavy.',
    exJ3: 'Those have already sold out.',
    exJ1Jp: 'あれらは新しい自転車です。',
    exJ2Jp: 'あれらは重そうに見えます。',
    exJ3Jp: 'あれらはすでに売り切れました。',
  },
  {
    group: PronounGroup.Demonstrative,
    term: 'such',
    ipa: '/sʌtʃ/',
    jp: 'そのようなもの、こと',
    exJ1: 'This is such a big dog.',
    exJ2: 'It was such a fun game.',
    exJ3: 'Such problems have happened in the past.',
    exJ1Jp: 'これはとても大きな犬です。',
    exJ2Jp: 'とても楽しい試合でした。',
    exJ3Jp: 'そのような問題は過去にも起きています。',
  },
  {
    group: PronounGroup.Demonstrative,
    term: 'same',
    ipa: '/seɪm/',
    jp: '同じもの、こと',
    exJ1: 'I chose the same.',
    exJ2: 'We have the same idea.',
    exJ3: 'They arrived at the same time as yesterday.',
    exJ1Jp: '私は同じものを選びました。',
    exJ2Jp: '私たちは同じ考えを持っています。',
    exJ3Jp: '彼らは昨日と同じ時間に到着しました。',
  },
];
