import { PronounItem } from './type';

export const DATA_RAW: Omit<PronounItem, 'index'>[] = [
  // 01. Personal / Possessive / Reflexive
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '一人称',
    term: 'I',
    ipa: '/aɪ/',
    jp: '私は',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '一人称',
    term: 'my',
    ipa: '/maɪ/',
    jp: '私の',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '一人称',
    term: 'me',
    ipa: '/miː/',
    jp: '私を、私に',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '一人称',
    term: 'mine',
    ipa: '/maɪn/',
    jp: '私のもの',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '一人称',
    term: 'myself',
    ipa: '/maɪˈsɛlf/',
    jp: '私自身',
  },

  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '一人称（複数）',
    term: 'we',
    ipa: '/wiː/',
    jp: '私たちは',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '一人称（複数）',
    term: 'our',
    ipa: '/ˈaʊɚ/',
    jp: '私たちの',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '一人称（複数）',
    term: 'us',
    ipa: '/ʌs/',
    jp: '私たちを、私たちに',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '一人称（複数）',
    term: 'ours',
    ipa: '/ˈaʊɚz/',
    jp: '私たちのもの',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '一人称（複数）',
    term: 'ourselves',
    ipa: '/ɑrˈsɛlvz/',
    jp: '私たち自身',
  },

  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '二人称（単数）',
    term: 'you',
    ipa: '/juː/',
    jp: 'あなたは',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '二人称（単数）',
    term: 'your',
    ipa: '/jʊr/',
    jp: 'あなたの',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '二人称（単数）',
    term: 'you',
    ipa: '/juː/',
    jp: 'あなたを、あなたに',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '二人称（単数）',
    term: 'yours',
    ipa: '/jʊrz/',
    jp: 'あなたのもの',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '二人称（単数）',
    term: 'yourself',
    ipa: '/jʊrˈsɛlf/',
    jp: 'あなた自身',
  },

  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '二人称（複数）',
    term: 'you',
    ipa: '/juː/',
    jp: 'あなたたちは',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '二人称（複数）',
    term: 'your',
    ipa: '/jʊr/',
    jp: 'あなたたちの',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '二人称（複数）',
    term: 'you',
    ipa: '/juː/',
    jp: 'あなたたちを、あなたたちに',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '二人称（複数）',
    term: 'yours',
    ipa: '/jʊrz/',
    jp: 'あなたたちのもの',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '二人称（複数）',
    term: 'yourselves',
    ipa: '/jʊrˈsɛlvz/',
    jp: 'あなたたち自身',
  },

  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（単数）',
    term: 'he',
    ipa: '/hiː/',
    jp: '彼は',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（単数）',
    term: 'his',
    ipa: '/hɪz/',
    jp: '彼の',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（単数）',
    term: 'him',
    ipa: '/hɪm/',
    jp: '彼を、彼に',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（単数）',
    term: 'his',
    ipa: '/hɪz/',
    jp: '彼のもの',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（単数）',
    term: 'himself',
    ipa: '/hɪmˈsɛlf/',
    jp: '彼自身',
  },

  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（単数）',
    term: 'she',
    ipa: '/ʃiː/',
    jp: '彼女は',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（単数）',
    term: 'her',
    ipa: '/hɝː/',
    jp: '彼女の',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（単数）',
    term: 'her',
    ipa: '/hɝː/',
    jp: '彼女を、彼女に',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（単数）',
    term: 'hers',
    ipa: '/hɝːz/',
    jp: '彼女のもの',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（単数）',
    term: 'herself',
    ipa: '/hɝːˈsɛlf/',
    jp: '彼女自身',
  },

  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（単数・無生物）',
    term: 'it',
    ipa: '/ɪt/',
    jp: 'それは',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（単数・無生物）',
    term: 'its',
    ipa: '/ɪts/',
    jp: 'それの',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（単数・無生物）',
    term: 'it',
    ipa: '/ɪt/',
    jp: 'それを、それに',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（単数・無生物）',
    term: 'itself',
    ipa: '/ɪtˈsɛlf/',
    jp: 'それ自身',
  },

  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（複数）',
    term: 'they',
    ipa: '/ðeɪ/',
    jp: '彼らは',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（複数）',
    term: 'their',
    ipa: '/ðɛr/',
    jp: '彼らの',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（複数）',
    term: 'them',
    ipa: '/ðɛm/',
    jp: '彼らを、彼らに',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（複数）',
    term: 'theirs',
    ipa: '/ðɛrz/',
    jp: '彼らのもの',
  },
  {
    group: 'Personal/Possessive/Reflexive',
    subGroup: '三人称（複数）',
    term: 'themselves',
    ipa: '/ðɛmˈsɛlvz/',
    jp: '彼ら自身',
  },

  // 02. Indefinite (person/thing)
  {
    group: 'Indefinite (person/thing)',
    subGroup: 'some 系',
    term: 'someone',
    ipa: '/ˈsʌmˌwʌn/',
    jp: '誰か',
  },
  {
    group: 'Indefinite (person/thing)',
    subGroup: 'some 系',
    term: 'somebody',
    ipa: '/ˈsʌmˌbɑːdi/',
    jp: '誰か',
  },
  {
    group: 'Indefinite (person/thing)',
    subGroup: 'some 系',
    term: 'something',
    ipa: '/ˈsʌmˌθɪŋ/',
    jp: '何か',
  },

  {
    group: 'Indefinite (person/thing)',
    subGroup: 'any 系',
    term: 'anyone',
    ipa: '/ˈɛniˌwʌn/',
    jp: '誰でも、誰か',
  },
  {
    group: 'Indefinite (person/thing)',
    subGroup: 'any 系',
    term: 'anybody',
    ipa: '/ˈɛniˌbɑːdi/',
    jp: '誰でも、誰か',
  },
  {
    group: 'Indefinite (person/thing)',
    subGroup: 'any 系',
    term: 'anything',
    ipa: '/ˈɛniˌθɪŋ/',
    jp: '何でも、何か',
  },

  {
    group: 'Indefinite (person/thing)',
    subGroup: 'every 系',
    term: 'everyone',
    ipa: '/ˈɛvriˌwʌn/',
    jp: 'みんな',
  },
  {
    group: 'Indefinite (person/thing)',
    subGroup: 'every 系',
    term: 'everybody',
    ipa: '/ˈɛvriˌbɑːdi/',
    jp: 'みんな',
  },
  {
    group: 'Indefinite (person/thing)',
    subGroup: 'every 系',
    term: 'everything',
    ipa: '/ˈɛvriˌθɪŋ/',
    jp: 'すべて',
  },

  {
    group: 'Indefinite (person/thing)',
    subGroup: 'no 系',
    term: 'no one',
    ipa: '/ˈnoʊ ˌwʌn/',
    jp: '誰も〜ない',
  },
  {
    group: 'Indefinite (person/thing)',
    subGroup: 'no 系',
    term: 'nobody',
    ipa: '/ˈnoʊˌbɑːdi/',
    jp: '誰も〜ない',
  },
  {
    group: 'Indefinite (person/thing)',
    subGroup: 'no 系',
    term: 'nothing',
    ipa: '/ˈnʌθɪŋ/',
    jp: '何も〜ない',
  },

  // 03. Indefinite (quantity/partitive)
  { group: 'Indefinite (quantity/partitive)', term: 'one', ipa: '/wʌn/', jp: '一人、もの' },
  {
    group: 'Indefinite (quantity/partitive)',
    term: 'another',
    ipa: '/əˈnʌðɚ/',
    jp: 'もう一つの、別の',
  },
  { group: 'Indefinite (quantity/partitive)', term: 'other', ipa: '/ˈʌðɚ/', jp: '他の' },
  {
    group: 'Indefinite (quantity/partitive)',
    term: 'others',
    ipa: '/ˈʌðɚz/',
    jp: '他のもの、人々',
  },
  { group: 'Indefinite (quantity/partitive)', term: 'each', ipa: '/itʃ/', jp: 'それぞれ' },
  { group: 'Indefinite (quantity/partitive)', term: 'either', ipa: '/ˈiðɚ/', jp: 'どちらか' },
  {
    group: 'Indefinite (quantity/partitive)',
    term: 'neither',
    ipa: '/ˈniðɚ/',
    jp: 'どちらも〜ない',
  },
  {
    group: 'Indefinite (quantity/partitive)',
    term: 'none',
    ipa: '/nʌn/',
    jp: 'どれも〜ない、誰も〜ない',
  },
  { group: 'Indefinite (quantity/partitive)', term: 'some', ipa: '/sʌm/', jp: 'いくつかの' },
  { group: 'Indefinite (quantity/partitive)', term: 'any', ipa: '/ˈɛni/', jp: 'いくらか、どれか' },
  { group: 'Indefinite (quantity/partitive)', term: 'certain', ipa: '/ˈsɝːtn/', jp: 'ある人々' },
  { group: 'Indefinite (quantity/partitive)', term: 'all', ipa: '/ɔl/', jp: 'すべて' },
  { group: 'Indefinite (quantity/partitive)', term: 'both', ipa: '/boʊθ/', jp: '両方' },
  { group: 'Indefinite (quantity/partitive)', term: 'most', ipa: '/moʊst/', jp: 'ほとんどの' },
  { group: 'Indefinite (quantity/partitive)', term: 'more', ipa: '/mɔr/', jp: 'もっと多くの' },
  { group: 'Indefinite (quantity/partitive)', term: 'many', ipa: '/ˈmɛni/', jp: '多くの（可算）' },
  { group: 'Indefinite (quantity/partitive)', term: 'much', ipa: '/mʌtʃ/', jp: '多くの（不可算）' },
  { group: 'Indefinite (quantity/partitive)', term: 'several', ipa: '/ˈsɛvrəl/', jp: 'いくつかの' },
  {
    group: 'Indefinite (quantity/partitive)',
    term: 'few',
    ipa: '/fjuː/',
    jp: 'ほとんど〜ない（可算）',
  },
  {
    group: 'Indefinite (quantity/partitive)',
    term: 'little',
    ipa: '/ˈlɪtl/',
    jp: 'ほとんど〜ない（不可算）',
  },
  { group: 'Indefinite (quantity/partitive)', term: 'less', ipa: '/lɛs/', jp: 'より少ない' },
  {
    group: 'Indefinite (quantity/partitive)',
    term: 'least',
    ipa: '/list/',
    jp: '最小、最も少ない',
  },
  { group: 'Indefinite (quantity/partitive)', term: 'enough', ipa: '/ɪˈnʌf/', jp: '十分な' },

  // 04. Demonstrative & Other
  { group: 'Demonstrative/Other', term: 'this', ipa: '/ðɪs/', jp: 'これ' },
  { group: 'Demonstrative/Other', term: 'these', ipa: '/ðiːz/', jp: 'これら' },
  { group: 'Demonstrative/Other', term: 'that', ipa: '/ðæt/', jp: 'それ、あれ' },
  { group: 'Demonstrative/Other', term: 'those', ipa: '/ðoʊz/', jp: 'それら、あれら' },
  { group: 'Demonstrative/Other', term: 'such', ipa: '/sʌtʃ/', jp: 'そのようなもの、こと' },
  { group: 'Demonstrative/Other', term: 'same', ipa: '/seɪm/', jp: '同じもの、こと' },
];
