import { IrregularVerb } from '../../../../../../shared/types';
import { IrregularVerbMatrix, LightHeightClass } from '../../../common/IrregularVerbMatrix';

/**
 * 不規則動詞のサンプルデータ
 */
const irregularVerbsData: IrregularVerb[] = [
  {
    infinitive: 'bend',
    past: 'bent',
    pastParticiple: 'bent',
    ing: 'bending',
    meaning: 'かがむ、〜を曲げる',
  },
  {
    infinitive: 'bring',
    past: 'brought',
    pastParticiple: 'brought',
    ing: 'bringing',
    meaning: '〜を持ってくる',
  },
  {
    infinitive: 'build',
    past: 'built',
    pastParticiple: 'built',
    ing: 'building',
    meaning: '〜を建てる、〜を構築する',
  },
  {
    infinitive: 'buy',
    past: 'bought',
    pastParticiple: 'bought',
    ing: 'buying',
    meaning: '〜を買う、〜を購入する',
  },
  {
    infinitive: 'catch',
    past: 'caught',
    pastParticiple: 'caught',
    ing: 'catching',
    meaning: '〜を捕まえる',
  },
  {
    infinitive: 'deal',
    past: 'dealt',
    pastParticiple: 'dealt',
    ing: 'dealing',
    meaning: '取引する、扱う',
  },
  {
    infinitive: 'feed',
    past: 'fed',
    pastParticiple: 'fed',
    ing: 'feeding',
    meaning: '〜に餌をやる、〜を養う',
  },
  {
    infinitive: 'feel',
    past: 'felt',
    pastParticiple: 'felt',
    ing: 'feeling',
    meaning: '〜を感じる、〜と思う、〜を探る',
  },
  {
    infinitive: 'fight',
    past: 'fought',
    pastParticiple: 'fought',
    ing: 'fighting',
    meaning: '戦う、争う',
  },
  {
    infinitive: 'find',
    past: 'found',
    pastParticiple: 'found',
    ing: 'finding',
    meaning: '〜を見つける、〜と思う',
  },
  {
    infinitive: 'hang',
    past: 'hung',
    pastParticiple: 'hung',
    ing: 'hanging',
    meaning: '〜を掛ける、〜を吊るす',
  },
  {
    infinitive: 'have',
    past: 'had',
    pastParticiple: 'had',
    ing: 'having',
    meaning: '〜を持っている',
  },
  {
    infinitive: 'hear',
    past: 'heard',
    pastParticiple: 'heard',
    ing: 'hearing',
    meaning: '〜が聞こえる（受動的）',
  },
  {
    infinitive: 'hold',
    past: 'held',
    pastParticiple: 'held',
    ing: 'holding',
    meaning: '〜を持つ、〜を握る',
  },
  {
    infinitive: 'keep',
    past: 'kept',
    pastParticiple: 'kept',
    ing: 'keeping',
    meaning: '〜を保つ、〜を維持する',
  },
  {
    infinitive: 'leave',
    past: 'left',
    pastParticiple: 'left',
    ing: 'leaving',
    meaning: '出発する、〜を去る',
  },
  { infinitive: 'lend', past: 'lent', pastParticiple: 'lent', ing: 'lending', meaning: '〜を貸す' },
  {
    infinitive: 'lose',
    past: 'lost',
    pastParticiple: 'lost',
    ing: 'losing',
    meaning: '負ける、〜を失う',
  },
  {
    infinitive: 'make',
    past: 'made',
    pastParticiple: 'made',
    ing: 'making',
    meaning: '〜を作る、〜にする',
  },
  {
    infinitive: 'mean',
    past: 'meant',
    pastParticiple: 'meant',
    ing: 'meaning',
    meaning: '〜を意味する',
  },
  {
    infinitive: 'meet',
    past: 'met',
    pastParticiple: 'met',
    ing: 'meeting',
    meaning: '会う、〜に会う',
  },
  { infinitive: 'pay', past: 'paid', pastParticiple: 'paid', ing: 'paying', meaning: '〜を支払う' },
  {
    infinitive: 'say',
    past: 'said',
    pastParticiple: 'said',
    ing: 'saying',
    meaning: '〜を言う、〜と述べる',
  },
  {
    infinitive: 'sell',
    past: 'sold',
    pastParticiple: 'sold',
    ing: 'selling',
    meaning: '〜を販売する',
  },
  {
    infinitive: 'send',
    past: 'sent',
    pastParticiple: 'sent',
    ing: 'sending',
    meaning: '〜を送る、〜を届ける',
  },
  {
    infinitive: 'shoot',
    past: 'shot',
    pastParticiple: 'shot',
    ing: 'shooting',
    meaning: '〜を撃つ（球）',
  },
  {
    infinitive: 'sit',
    past: 'sat',
    pastParticiple: 'sat',
    ing: 'sitting',
    meaning: '座る、座っている',
  },
  { infinitive: 'sleep', past: 'slept', pastParticiple: 'slept', ing: 'sleeping', meaning: '眠る' },
  {
    infinitive: 'slide',
    past: 'slid',
    pastParticiple: 'slid',
    ing: 'sliding',
    meaning: '滑る、〜を滑らせる',
  },
  {
    infinitive: 'spend',
    past: 'spent',
    pastParticiple: 'spent',
    ing: 'spending',
    meaning: '〜を費やす（時間、お金）',
  },
  {
    infinitive: 'stand',
    past: 'stood',
    pastParticiple: 'stood',
    ing: 'standing',
    meaning: '立つ、立っている、〜を我慢する',
  },
  {
    infinitive: 'teach',
    past: 'taught',
    pastParticiple: 'taught',
    ing: 'teaching',
    meaning: '〜を教える',
  },
  {
    infinitive: 'tell',
    past: 'told',
    pastParticiple: 'told',
    ing: 'telling',
    meaning: '〜を伝える、〜に命じる',
  },
  {
    infinitive: 'think',
    past: 'thought',
    pastParticiple: 'thought',
    ing: 'thinking',
    meaning: '考える、〜と考える（意見）',
  },
  {
    infinitive: 'understand',
    past: 'understood',
    pastParticiple: 'understood',
    ing: 'understanding',
    meaning: '〜を理解する（解釈する）',
  },
  {
    infinitive: 'win',
    past: 'won',
    pastParticiple: 'won',
    ing: 'winning',
    meaning: '勝つ、〜を勝ち取る',
  },
];

export const ABBMatrix: React.FC = () => {
  return <IrregularVerbMatrix data={irregularVerbsData} lightHeightClass={LightHeightClass.ABB} />;
};
